version: "3.8"

services:
  pipelines:
    image: ghcr.io/open-webui/pipelines:main

    ports:
      - "9099:9099"

    volumes:
      # 使用 named volume
      - pipelines:/app/pipelines

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: always

    container_name: pipelines

volumes:
  pipelines:
